version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/clients/typescript"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend/react-sketchlog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/wasm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/clients/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
